Allow HTTP port configuration

diff --git a/play b/play
--- a/play
+++ b/play
@@ -5,8 +5,23 @@ if [ -f conf/application.conf ]; then
     `dirname $0`/framework/cleanIvyCache
   fi
   if test "$1" = "stop"; then
-    kill `cat RUNNING_PID`
-    exit $?
+    if [ -f RUNNING_PID ]; then
+      echo "[info] Stopping application (with PID `cat RUNNING_PID`)..."
+      kill `cat RUNNING_PID`
+
+      RESULT=$?
+
+      if test "$RESULT" = 0; then
+        echo "[info] Done!"
+        exit 0
+      else
+        echo "[\033[31merror\033[0m] Failed ($RESULT)"
+        exit $RESULT
+      fi
+    else
+      echo "[\033[31merror\033[0m] No RUNNING_PID file. Is this application running?"
+      exit 1
+    fi
   fi
   if [ -n "$1" ]; then
     `dirname $0`/framework/build "$@"
