Getting starter experience improvements (#8385)
* Remove unused images

* Moving "Installing" to "Requirements"

* Revamping the getting started experience

* Fix validateDocs

* Fixes/improvements after review

* Move views and route files

* Compile getting started code samples

* Update missing copyright notices

* Add missing copyright headers

* Check copyright header for markdown docs

* Minor corrections and improvements after review

* Add target to localhost links

* Some rewording

* Adding numbers to tutorial sections

* Small reorganization of tutorial docs

* Fix test-docs build

* Add missing headers

* Fix issues suggested by Ignasi

diff --git a/framework/bin/test-docs b/framework/bin/test-docs
--- a/framework/bin/test-docs
+++ b/framework/bin/test-docs
@@ -12,3 +12,14 @@ runSbtNoisy evaluateSbtFiles
 runSbt validateDocs
 
 printMessage "ALL DOCUMENTATION TESTS PASSED"
+
+# Check that markdown files have copyright headers
+
+./addMarkdownCopyright
+
+git diff --exit-code || (
+  echo "ERROR: Documentation copyright check failed, see differences above."
+  echo "To fix, run './addMarkdownCopyright' script inside documentation directory."
+  echo "After that you can update your pull request."
+  false
+)
